name: 'wp'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - database:/var/lib/mysql;
    env_file: .env
    ports:
      - "3306:3306"
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - website:/var/www/html
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - website:/var/www/html
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    restart: always

volumes:
  website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/picatrai/data/website'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/picatrai/data/database

networks:
  inception:
    name: inception
    driver: bridge
