version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql;
    env_file: .env
    expose:
      - "3306"

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/picatrai/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/picatrai/data/mariadb


networks:
  inception:
    driver: bridge

#volumes:
#  mariadb_data:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/picatrai/data/mysql
#     o: bind
#  wordpress_data:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/picatrai/data/wordpress
#      o: bind
