-- CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
-- CREATE USER IF NOT EXISTS '${USER_NAME}'@'%' IDENTIFIED BY '${USER_PASSWORD}';
-- GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${USER_NAME}'@'%';
-- ALTER USER 'root'@'localhost' IDENTIFIED BY '${ADMIN_PASSWORD}';
-- FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'picatrai'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'picatrai'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
